config/routes.rb
Reporter::Application.routes.draw do
  devise_for :users

  match '/auth/:provider/callback' => 'authentications#create'

  mount Base::Api => '/'

  namespace :admin do
  end

  resources :reports

  root :to => 'reports#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user

  attr_accessible :description, :height, :length, :name, :width, :user_id

  validates :description, :height, :length, :name, :width, :user_id, presence: true
  validates :height, :length, :width, :user_id, numericality: true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users

  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :role

  has_many :reports

  belongs_to :role

  after_create :add_role

  delegate :name, to: :role, prefix: true

  private

  def add_role
    self.role = Role.find_by_name('reporter')
    save
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_report, except: [:new, :create]

  def index
    @reports = current_user.reports
    @reports = Filter.new(@reports, params[:filter]).execute if params[:filter]
    @reports = Sort.new(@reports, params[:sort][:field], params[:sort][:direction]).execute if params[:sort]

    respond_to do |format|
      format.html
      format.json { render json: @reports }
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @report }
    end
  end

  def new
    @report = Report.new

    respond_to do |format|
      format.html
      format.json { render json: @report }
    end
  end

  def create
    @report = Report.new(params[:report].merge(user_id: current_user.id))

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def update

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to reports_path, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
      format.js
    end
  end

  private

  def find_report
    @report = Report.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    Constants::ALERT_TYPES[type]
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/_header.html.slim
.navbar
  .navbar-inner
    .row-fluid
      .span12
        .pull-left
          h3 AWESOME LOGO
        - if user_signed_in?
          .pull-right
            = link_to 'REPORTS', reports_path
            | &emsp;
            = link_to 'SIGN OUT', destroy_user_session_path, method: :delete
        - else
          .nav-collapse.collapse
            ul.nav.pull-right
              li.active
                = link_to 'HOME', root_path
              li
                = link_to 'SIGN UP', new_user_registration_path
              li
                = link_to 'LOG IN', new_user_session_path

app/views/layouts/application.html.slim
doctype
html
  head
    title Reporter
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
body
  header
    .container-fluid
      .inline-block
        = render partial: 'layouts/header'
  .container-fluid.content-container
    = render partial: 'shared/flash_messages'
    = yield
    div#modal_window.modal.hide.fade

app/views/reports/_form.html.slim
= form_for @report do |f|
  - if @report.errors.any?
    #error_explanation
      h2 = "#{pluralize(@report.errors.count, "error")} prohibited this report from being saved:"
      ul
        - @report.errors.full_messages.each do |message|
          li = message

  .row-fluid
    .span12
      .row-fluid
        .span4= f.label :name
        .span8= f.text_field :name
      .row-fluid
        .span4= f.label :description
        .span8= f.text_field :description
      .row-fluid
        .span4= f.label :height
        .span8= f.text_field :height
      .row-fluid
        .span4= f.label :width
        .span8= f.text_field :width
      .row-fluid
        .span4= f.label :length
        .span8= f.text_field :length
      .row-fluid
        .actions = f.submit 'Save'

app/views/reports/_report.html.slim
.row-fluid id="report_#{report.id}"
  .span2 = report.name
  .span4 = report.description
  .span1 = report.height
  .span1 = report.width
  .span1 = report.length
  .span1 = link_to 'Show', report
  .span1 = link_to 'Edit', edit_report_path(report), remote: true
  .span1 = link_to 'Destroy', report, confirm: 'Are you sure?', method: :delete, remote: true

app/views/reports/destroy.js.slim
| $("#report_#{@report.id}").remove();

app/views/reports/edit.html.slim
h1 Editing report
.block
  = render 'form'
  = link_to 'Show', @report
  | &emsp;
  = link_to 'Back', reports_path

app/views/reports/edit.js.slim
| $('#modal_window').modal('show');
| $('#modal_window').html("#{j(render partial: 'form')}");

app/views/reports/index.html.slim
.block
  h1 Listing reports

  #reports.row-fluid
    .row-fluid
      = form_for :filter, url: reports_path, method: 'GET' do |f|
        .span3= f.select :by, options_for_select(Constants::Report::FILTER)
        .span3= f.text_field :param
        .span3= f.submit 'Filter', class: 'btn'
    .row-fluid
      .span2 = link_to 'Name', reports_path(sort: { field: :name, direction: "ASC" } )
      .span4 = link_to 'Description', reports_path(sort: { field: :description, direction: "ASC" } )
      .span1 = link_to 'Height', reports_path(sort: { field: :height, direction: "ASC" } )
      .span1 = link_to 'Width', reports_path(sort: { field: :width, direction: "ASC" } )
      .span1 = link_to 'Length', reports_path(sort: { field: :length, direction: "ASC" } )
      .span1
      .span1
      .span1
    = render partial: 'report', collection: @reports
  .row-fluid= link_to 'New Report', new_report_path

app/views/reports/new.html.slim
h1 New report

== render 'form'

= link_to 'Back', reports_path

app/views/reports/show.html.slim
.block
  .row-fluid
    .span3
      strong Name:
    .span6
      = @report.name
  .row-fluid
    .span3
      strong Description:
    .span6
      = @report.description
  .row-fluid
    .span3
      strong Height:
    .span6
      = @report.height
  .row-fluid
    .span3
      strong Width:
    .span6
      = @report.width
  .row-fluid
    .span3
      strong Length:
    .span6
      = @report.length

  = link_to 'Edit', edit_report_path(@report), class: 'btn'
  | &emsp;
  = link_to 'Back', reports_path, class: 'btn'

app/views/shared/_flash_messages.html.slim
- flash.each do |key, value|
  div class="#{flash_class(key)}"
    = value